# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-06 09:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.CharField(default=datetime.datetime(2020, 3, 6, 9, 2, 4, 949361, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
