# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20200306_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
